language: ruby
before_install:
  - gem install bundler -v 1.7.7
bundler_args: --without guard
script:
  - "bundle exec rspec spec"
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
